// functions/_slugmap.js
// Mappe: slugify(title) -> filename.json
export const slugToFile = {
  "15_de_romance": "5_no_Renai_Kanjou_(Doujinshi).json",
  "aaa": "AAA_(Doujinshi).json",
  "amour_eternel_-_mirrored_lotus": "Mirrored_Lotus _(Doujinshi).json",
  "an_invisible_kiss": "An_Invisible_Kiss.json",
  "angelic_transfer_studentchan__mastophobia-kun": "Tenshi_na_Tenkousei_chan_to_Kyonyuu_Kyoufushou_kun.json",
  "bocchi_the_rock_anthology_comic": "Bocchi_the_Rock!_Anthology_Comic.json",
  "compte_secondaire__ton_secret_mappartient_": "Alt_Account_Trap.json",
  "enjo_kouhai": "Enjo_Kouhai _(Doujinshi).json",
  "faire_fondre_ton_cur_en_melant_nos_chaleurs": "Netsu_o_Mazete_Shin_o_Tokashite_(Doujinshi).json",
  "fermier_dans_un_autre_monde": "Isekai_Nonbiri_Nouka.json",
  "fete_du_nouvel_an_avec_le_groupe_detude": "Fête_du_Nouvel_An_avec_le_groupe_d'étude_(Doujinshi).json",
  "gentle_connect_redive": "Gentle_Connect_ReDive_(Doujinshi).json",
  "girls__vampire": "Girls_×_Vampire.json",
  "hakari_et_karane_le_livre_ou_elles_maiiiment_a_en_mourir": "Hakari_to_Karane_to_IchaLove_H_suru_HON_(Doujinshi).json",
  "halloween_2023": "Hallowwen_2023_(Doujinshi).json",
  "harem_in_the_labyrinth_of_another_world": "Isekai_Meikyuu_de_Harem_wo.json",
  "hiroi_kikuri_ivre_morte_passe_une_tres_mauvaise_nuit": "Hiroi_kikuri_ivre_morte_passe_une_très_mauvaise_nuit._(Doujinshi).json",
  "hoshino_veut_aussi_se_faire_dorloter_": "Hoshino_datte_Amaetai _(Doujinshi).json",
  "i_need_more_power": "I_NEED_MORE _POWER_(Doujinshi).json",
  "iku_suto": "Iku_Sutou_(Doujinshi).json",
  "je_les_domine_tous_en_tant_que_porteur_dans_cet_autre_monde": "Je_les_domine_tous_en_tant_que_porteur_dans_cet_autre_monde.json",
  "je_nai_que_la_magie_de_leau_mais_mes_connaissances_modernes_suffisent": "Mizu_Mahou_Gurai_Shika_Torie_ga_Nai_Kedo_Gendai_Chishiki_ga_Areba_Juubun_da_yo_ne.json",
  "je_suis_arrive_dans_un_autre_monde_alors_je_vais_utiliser_la_magie_pour_faire_des_cochonneries": "Isekai_Kita_no_de_Mahou_o_Sukebe_na_Koto_ni_Riyou_Shiyou_to_Omou_(Doujinshi).json",
  "je_suis_suis_le_serviteur_dune_petite_succube": "Boku_wa_Chiisana_Succubus_no_Shimobe_Soushuuhen_(Doujinshi).json",
  "je_ten_supplie_enfile-les_takamine_": "Haite_Kudasai_Takamine_san.json",
  "jour_apres_jour": "Mane_Mane_Nichi_Nichi.json",
  "kokona_la_mignonne_petite_chienne": "Kokona_la_mignonne_petite_chienne_(Doujinshi).json",
  "la_capitaine_marine_veut_etre_violee_de_facon_non-consentie": "Marine_Senchou_wa_Hi_Goui_no_Ue_de_Wakarasaretai_(Doujinshi).json",
  "la_courageuse_demande_du_nomade": "Rover's_Brave_Request_(Doujinshi).json",
  "la_deleguee_et_la_delinquante": "La_Déléguée_et_la_Délinquante.json",
  "la_fiancee_de_la_vilaine": "Akuyaku_Reijou_no_Oyome-sama.json",
  "la_gratitude_dune_bete": "La_gratitude_dune_bête_(Doujinshi).json",
  "la_luxurieuse_megi_cherie__moi_au_love_hotel_jusquau_petit_matin": "La_luxurieuse_Megi_chérie_&_moi_au_love_hotel_jusqu_au_petit_matin_(Doujinshi).json",
  "la_magie_dagrandissement_du_penis": "Chinchin_ga_Ookiku_Naru_Mahou_(Doujinshi).json",
  "la_nuit_de_la_constellation_ryuukin": "La_nuit_de_la_constellation_Ryuukin_(Doujinshi).json",
  "la_perverse_du_bureau_da_cote_narrete_pas_de_me_lancer_ce_genre_de_regards": "Perverse.json",
  "la_plus_mignonne_des_filles_a_mes_cotes": "La_plus_mignonne_des_filles_à_mes_côtés.json",
  "la_premiere_nuit_de_bocchi_et_kita": "La_première_nuit_de_Bocchi_et_Kita.json",
  "la_presidente_lalcool_et_les_etoiles": "Shachou_to_Sake_to_Hoshi.json",
  "la_succube_dominee_par_une_lesbienne": "La_succube_dominée_par_une_lesbienne_(Doujinshi).json",
  "lamour_a_sens_unique_de_momoi": "Momoiro_no_Kataomoi_(Doujinshi).json",
  "le_bar_a_hotesse_genshin": "Le_Bar_À_Hôtesse_Genshin_(Doujinshi).json",
  "le_chasseur_de_peches": "Le_Chasseur_de_Pêches_(Doujinshi).json",
  "le_muscle_et_la_potelee": "Chubby.json",
  "le_porte_bonheur_de_mademoiselle_kaguya": "Kaguya_sama_no_Enmusubi_(Doujinshi).json",
  "le_quotidien_de_sa-chan_une_employee_de_pharmacie": "Sa_Chan.json",
  "les_amies_du_chevalier_le_soignent_avec_leur_corps": "Kenshi_sama_o_Karada_de_Iyasu_Nakama_tachi_(Doujinshi).json",
  "les_aventures_dun_vieil_homme_transforme_en_une_loli_arc_de_la_masturbation": "Les_aventures_d_un_vieil_homme_transformé_en_une_loli_arc_de_la_masturbation_(Doujinshi).json",
  "les_bulles_obscenes_et_reves_sucres": "Les_bulles_obscènes_et_rêves_sucrés_(Doujinshi).json",
  "les_deux_races_les_plus_fortes_de_leur_monde_se_dechainent_apres_avoir_bu_une_potion_louche_": "Saikyoushu_no_Futari_ga_Nanika_Ayashii_Potion_de_Ecchi_ni_Nacchatta.json",
  "les_galeres_de_karubi": "Karubi_momareru.json",
  "les_vacances_d_yoimiya": "Yoimiya_Bakansu_(Doujinshi).json",
  "linnocence_sur_un_plateau": "Junketsu_no_Sainou_(Doujinshi).json",
  "live_in_dependence": "Live_In_Dependence_(Doujinshi).json",
  "ma_vie_de_reve_dans_un_autre_monde": "Ma_Vie_de_Rêve_dans_un_Autre_Monde_(Doujinshi).json",
  "megumin_et_lentrainement_a_lexplosion_lubrique_": "Kono_Sukebe_na_Bakuretsu_Musume_ni_Tyoukyou _wo_(Doujinshi).json",
  "miku_est_seule_a_noel": "Chri_Bocchi_Miku_(Doujinshi).json",
  "montre-moi_tes_dents_de_requin": "Kimi_no_Gizaba_ga_Mitemitai.json",
  "mounting_olympus": "MountingOlympus.json",
  "my_fluffy_neighbor": "MyFluffyNeighbor.json",
  "on_est_tes_esclaves_alors_tu_peux_faire_ce_que_tu_veux_diablo_": "Diablo_no_Shoyuubutsu_dakara_Suki_ni_Shite_mo_ii_yo....json",
  "pour_le_bien_de_ses_recherches_mona_sadonne_au_sexe": "Doujinshi_ni_Ireru_Mona_no_Ecchi_na_Manga_(Doujinshi).json",
  "prend_donc_plaisir_ho_aventurier_merveilleux_": "Kono_Subarashii_Boukensha_ni_Kairaku_o_(Doujinshi).json",
  "ptd-ero2": "PTD-Ero2_(Doujinshi).json",
  "redo_of_healer": "Kaifuku_Jutsushi_no_Yarinaoshi.json",
  "rendez-vous_nocturne": "Rendez-vous_Nocturne_(Doujinshi).json",
  "rentaro_et_maman_hahari_mode_demploi_lubrique_pour_cajoler_son_bebe": "Hahari-mama_to_Icha-babu_Ecchi_suru_Hon _(Doujinshi).json",
  "rin_et_nadeshiko_nuit_au_camping": "Rin_et_Nadeshiko_Nuit_au_Camping_(Doujinshi).json",
  "rosa_hypnotisee": "Mei-chan_saimin_manga_(Doujinshi).json",
  "seduire_une_loli_megumin_": "Lolikko_Megumin_o_Kouryaku_Seyo_(Doujinshi).json",
  "sorcellerie_harem_de_yokai": "Yokai_Harem.json",
  "stupide_furina": "Stupid_Furina_(Doujinshi).json",
  "sugary_days": "Sugary_Days.json",
  "the_manager_and_the_oblivious_waitress": "Tenchou_to_Mujikakuna_Tennin.json",
  "toradora_the_porn_book": "Toradora_no_Erohon_(Doujinshi).json",
  "trop_honnete_pour_quelquun_qui_parle_kyoto_": "Trop_honnête_pour_quelquun_qui_parle_Kyoto_!.json",
  "un_an_plus_tard_on_seclate_toujours_comme_des_petits_fous": "Ichinengo_no_Itazura_(Doujinshi).json",
  "un_entrainement_special_a_deux": "Futari_no_Tokubetsu_Kunren_(Doujinshi).json",
  "un_jour_dans_la_vie_de_chisato": "Chisato_no_1_nichi_(Doujinshi).json",
  "une_gyaru_deprimee_un_peu_trop_envahissante": "Kyori-kan_ga_Bagutteru_Downer_Gyaru-chan.json",
  "une_histoire_sur_une_fille_solitaire_qui_a_retenu_mon_attention": "Ippiki_Ookami_na_Onnanoko_ga_Kininaru_Hanashi.json",
  "vivre_ensemble_avec_kayoko": "Kayoko_to_Dousei_Seikatsu_(Doujinshi).json",
  "vivre_hospitalise_dans_un_autre_monde": "Hospitalized_Life_in_Another_World.json"
};
