name = "les-poroiniens-functions"
compatibility_date = "2025-08-22"

[[kv_namespaces]]
binding = "IMG_CHEST_CACHE"
id = "f2e590071fcb42419beaf126408af9b4"

[[kv_namespaces]]
binding = "INTERACTIONS_LOG"
id = "23ecbbac077642b0bebac89ccc79bc23"

[[kv_namespaces]]
binding = "INTERACTIONS_CACHE"
id = "5738ead5287d4c4e9fc1735835c2b266"

[vars]
ADMIN_USERNAME = ""
ADMIN_PASSWORD = ""
ADMIN_TOKEN = ""
